### ISSUE TITLE
Respect graph mode

### ISSUE THREAD

**Issue by staelche** [flyersa/MuninMX-Frontend#11]
Did you have a reason why do you not respect the graph mode (if possible) specified by the plugin with `.draw`? Even if not all modes are supported on the web frontend in some cases a mapping would be possible.

What do you think? Worth an optimization?

**Comment by flyersa** [comment]
Its more or less a dead project to be honest. I dont have much time to spend on it, thats why its here in the first place ;)

**Comment by staelche** [comment]
What a pitty.

But thats what I wanted to know. :-) Let's see if I can find some time for it. Because I really want to get rid of the regular munin installation...
