### ISSUE TITLE
Node names

### ISSUE THREAD

**Issue by kevinvalk** [flyersa/MuninMX-Frontend#3]
This is a well deserved modernization of munin, good stuff!

Sadly, I have a problem with my setup and muninmx. All my nodes are connected through ssh tunnels to the master server that is running muninmx. However, muninmx frontend only support hostname as naming for nodes (and it is also an index field in the database). This means that I can only have two nodes, localhost and 127.0.0.1. 

My suggestion is add an optimal name field to the nodes table and remove the "index" from the hostname. Whenever, name is set, show that instead of the hostname in the frontend.

This brings me to the next part. MuninMX just recently went open source and it feels a little bit chunky to be honest in its setup etc. So what is your take on improvements from the community? Because this sounds like a fun side project to work on.

**Comment by flyersa** [comment]
Hi,

that change is easily possible i think. I know its chunky and at the moment not so good to setup. But to be honest i do not have much time lately to work on anything in my spare time. I have a little daughter and my job is utilizing me to its full extend at the moment.

The complete setup and update process needs to be defined, preferable using system packages i think.

**Comment by kevinvalk** [comment]
Thank you for your response. Yes, totally understandable, I am currently abroad so I have the luxury that my weekends are completely free. I shall fork the frontend and make that change.

Perhaps you could take a look at seafile how they do their deployment, they have a similar architecture with php frontend and backend server(s). http://manual.seafile.com/deploy/using_mysql.html
