### ISSUE TITLE
Requests to graph.php taking a long time

### ISSUE THREAD

**Issue by staelche** [flyersa/MuninMX-Frontend#9]
I experience very long response times for ajax requests to graph.php to loading graphs. They are most of the times 8 seconds or longer. 

During this time (scrolling down and let muninmx load new graphs) mongodb (tokumx) has a cpu usage of nearly 100%. If I close the UI and observe just the collectors duing its job mongodb hardly uses the cpu. So I assume something is not well optimized when loading the graph data?! I followed your installation guide and didn't configure mongodb in any special way.

I am running muninmx on my test VM with 2 cores and 2 GB memory and monitor one node with a good amount of graphs (20-30).

**Comment by flyersa** [comment]
Hi do you have this after a long time of have muninmx running? Please add a crontab for the index jobs:

*/55 * * * * cd /var/www/html/cron; php createIndexes.php > /tmp/index.log
*/30 * * * * cd /var/www/html/cron; php update_uptime.php > /tmp/uptime.log

**Comment by staelche** [comment]
Mh. My bad. Just read the installation instruction on the web page not the INSTALL file of the installer bundle.

Mybe you should either update the instructions on the page or point on the page to that file for more details. :-)
